stages:
    - lint
    - test

variables:
    NPM_CACHE_DIR: "$CI_PROJECT_DIR/.npm"

cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
        - $NPM_CACHE_DIR

front-lint-job:
    image: node:21
    stage: lint
    script:
        - cd front
        - npm ci --cache $NPM_CACHE_DIR --prefer-offline
        - npm run lint

back-lint-job:
    image: node:21
    stage: lint
    script:
        - cd back
        - npm ci --cache $NPM_CACHE_DIR --prefer-offline
        - npm run lint

front-jest-test-job:
    image: node:21
    stage: test
    script:
        - cd front
        - npm ci --cache $NPM_CACHE_DIR --prefer-offline
        - npm run test
